# -*- coding: utf-8 -*-
"""Stubs de typage pour le paquet `qhyccd` (caméras QHYCCD) — jalon 100.

`qhyccd` est un binding natif (Rust/PyO3) SANS annotations et OPTIONNEL
(cf. requirements.txt). Ces stubs sont lus par `pyright` via
`stubPath = avastack/stubs` (pyproject.toml) : ils décrivent la surface
RÉELLEMENT utilisée par `avastack/cameras/qhy.py`, sans prétendre couvrir tout
le SDK. Fichier de DÉVELOPPEMENT uniquement — jamais embarqué dans
l'application, ne change AUCUN comportement.
"""

import numpy as np

# --- Fonctions de module -----------------------------------------------------

def init_sdk() -> None:
    """Initialise le SDK natif (UNE seule fois par processus)."""
    ...

def scan_cameras() -> "list[str]":
    """Noms des caméras QHY branchées (sans les ouvrir)."""
    ...

# --- Classe Camera ----------------------------------------------------------
# ATTENTION : le CONSTRUCTEUR ouvre DÉJÀ la caméra (doc officielle) — ne
# jamais appeler open() ensuite (double ouverture = segfault natif).

class Camera:
    """Une caméra QHYCCD OUVERTE par le constructeur."""

    def __init__(self, camera_id: str) -> None: ...
    def set_stream_mode(self, mode: int) -> None: ...
    def init(self) -> None: ...
    def set_bin_mode(self, x: int, y: int) -> None: ...
    def set_resolution(self, x: int, y: int, w: int, h: int) -> None: ...
    def begin_live(self) -> None: ...
    def stop_live(self) -> None: ...
    def get_live_frame(self) -> np.ndarray: ...
    def set_exposure(self, microseconds: int) -> None: ...
    def set_gain(self, gain: float) -> None: ...
    def is_control_available(self, control_id: int) -> bool: ...
    def set_param(self, control_id: int, value: float) -> None: ...
    def get_param(self, control_id: int) -> float: ...
    def close(self) -> None: ...
